// apps/lit-demo/src/views/home-view.ts
import {html, LitElement} from 'lit';

import '../examples/menu-example';
import '../examples/nested-menu-example';
import '../examples/modal-example';
import '../examples/popover-example';
import '../examples/tooltip-example';
import '../examples/client-point-example';
import '../examples/combobox-example';

class LitHomeView extends LitElement {
  protected createRenderRoot() {
    return this;
  }

  render() {
    return html`
      <section class="hero-stage" aria-labelledby="stage-title">
        <div class="stage-grid"></div>
        <div class="stage-copy">
          <span class="section-kicker">01 / observe</span>
          <h2 id="stage-title">The DOM is<br /><span>the canvas.</span></h2>
          <p>Each card is an independent Lit component with a Light DOM render root and its own FloatingController pipeline.</p>
        </div>
        <div class="signal-orbit" aria-hidden="true">
          <span class="orbit-ring ring-one"></span><span class="orbit-ring ring-two"></span>
          <span class="orbit-dot dot-a"></span><span class="orbit-dot dot-b"></span><span class="orbit-dot dot-c"></span><span class="orbit-core"></span>
        </div>
        <div class="stage-readout"><span>ROUTE MAP</span><strong>/ · /examples/:primitive</strong></div>
      </section>
      <section class="demo-grid" aria-label="Lit interaction examples">
        <lit-tooltip-example></lit-tooltip-example>
        <lit-popover-example></lit-popover-example>
        <lit-menu-example></lit-menu-example>
        <lit-nested-menu-example></lit-nested-menu-example>
        <lit-client-point-example></lit-client-point-example>
        <lit-combobox-example></lit-combobox-example>
        <a class="demo-card placement-card" href="/examples/placement">
          <div class="card-top">
            <span class="number">P</span><span class="chip">12 typed directions</span>
          </div>
          <h3>Placement constants</h3>
          <p>Choose every side and alignment without repeating string literals.</p>
          <div class="card-action">
            <span class="outline-button">Open placement lab <span>↗</span></span>
          </div>
          <code>PLACEMENT.BOTTOM_START</code>
        </a>
      </section>
      <lit-modal-example></lit-modal-example>
    `;
  }
}

customElements.define('lit-home-view', LitHomeView);

// apps/vue-demo/src/views/HomeView.vue
<script setup lang="ts">
import {RouterLink} from 'vue-router';
import ExampleClientPoint from '../components/ExampleClientPoint.vue';
import ExampleMenu from '../components/ExampleMenu.vue';
import ExampleModal from '../components/ExampleModal.vue';
import ExampleNestedMenu from '../components/ExampleNestedMenu.vue';
import ExamplePopover from '../components/ExamplePopover.vue';
import ExampleTooltip from '../components/ExampleTooltip.vue';
</script>

<template>
  <section class="vue-hero" aria-labelledby="vue-stage-title">
    <div class="vue-hero-grid" />
    <div class="relative z-10 max-w-md">
      <span class="vue-kicker text-vue-green">01 / compose</span>
      <h2 id="vue-stage-title">State flows<br /><em>into space.</em></h2>
      <p>Every card is a Composition API example: refs stay local, the Web kernel stays shared, and Vue owns rendering.</p>
    </div>
    <div class="vue-orbit" aria-hidden="true"><i /><i /><i /><b /></div>
    <div class="relative z-10 self-end justify-self-end font-mono text-[10px] uppercase tracking-[.08em] text-slate-300">ROUTE MAP<br /><strong class="text-vue-green">/examples/:primitive</strong></div>
  </section>
  <section class="vue-demo-grid" aria-label="Vue interaction examples">
    <ExampleTooltip />
    <ExamplePopover />
    <ExampleMenu />
    <ExampleNestedMenu />
    <ExampleClientPoint />
    <article class="vue-demo-card vue-placement-card">
      <div class="vue-card-top">
        <span class="vue-number">P</span>
        <span>12 typed directions</span>
      </div>
      <h3>Placement constants</h3>
      <p>Choose every side and alignment without repeating string literals.</p>
      <div class="mt-auto pt-7">
        <RouterLink class="vue-button vue-button-outline no-underline" to="/placement">
          Open placement lab <span>↗</span>
        </RouterLink>
      </div>
      <code>PLACEMENT.BOTTOM_START</code>
    </article>
  </section>
  <ExampleModal />
</template>
